### PR TITLE
Update docs to use extension in wikilink definition

### PR DESCRIPTION
**Pull request by riccardoferretti**
This will enable to navigate the documentation within github!
It is an updated version of #159 

Two main changes:
- Turns on `foam.edit.linkReferenceDefinitions: withExtensions`
- update existing docs with the new definitions

### CODE REVIEW

**Review by ingalless — COMMENTED** [review]
Looks good to me. The only thing I wonder is should we update this line in the `readme.md`?

```
Hello friend! Looks like you're reading this page on GitHub. Please go to the 👉rendered Foam Workspace for an improved experience!
```

**Comment by riccardoferretti** [comment]
That's a great point, will address that later today

**Comment by riccardoferretti** [comment]
@ingalless done, let me know if there is anything else, thanks!

**Review by ingalless — APPROVED** [review]
Great work! Looks good to me. LGTM!

**Pull request merged**
