### PR TITLE
extension descriptions now reflect .vscode dir

### PR DESCRIPTION
**Pull request by dcarosone**
including that image pasting is now supported natively

### CODE REVIEW

**Comment by dcarosone** [comment]
But I'm unclear why we no longer recommend Markdown All-in-One?
I've moved it below the break, unless there's a reason it's no longer recommended at all?  PR marked draft until this is clarified.

**Comment by riccardoferretti** [comment]
My bad, markdown all in one is still recommended

**Comment by dcarosone** [comment]
> My bad, markdown all in one is still recommended

Ok then it should still be in the `.vscode/extensions.json` ?

**Comment by riccardoferretti** [comment]
Yup, I am fixing that shortly. I also need to figure out why it's not copying the directory in the right place. Will be done in the next couple of hours

**Comment by riccardoferretti** [comment]
Thanks for pointing it out, I had missed that I had removed markdown AIO from the list of extensions, I was thinking of markdown-notes when I removed that line, thinking it was still on the list although we no longer use it

**Comment by dcarosone** [comment]
> I also need to figure out why it's not copying the directory in the right place.

In the GHA? Wasn't that because of my typo (extra s)? With that fixed, the additional mkdir can also be removed.

**Review by riccardoferretti — APPROVED** [review]

**Comment by riccardoferretti** [comment]
Yup the issue was around that. All fixed now, thanks!

**Pull request merged**
