### PR TITLE
Added support for direct links

### PR DESCRIPTION
**Pull request by riccardoferretti**
After this PR, connections between notes can be expressed both as `[[wikilink]` and as a regular link to the file `[link](path/to/file.md)`

### CODE REVIEW

**Comment by jmg-duarte** [comment]
Currently the feature does not work (well, it does but not as expected).
I tested it on my most used workspace and found out all kinds of links are being treated as connections.

This is the node of a single document where I review some Rust crates
image
The abundance of links is due to having several internet urls.

The current version, full graph looks like this:
image

**Comment by riccardoferretti** [comment]
Yes good point, the original idea was to add external links in the model but filter them out in the graph (by default). 

Given the possibly large amount of external links, and its impact on the model, I will actually filter them out for now, until there is a good reason to expose them (which will then require some performance testing).

**Comment by jmg-duarte** [comment]
When Ctrl+Click'ing on a crossreference (any link that does not have a file) I get the following stack trace:
```
rejected promise not handled within 1 second: TypeError: Cannot read property 'uri' of null
extensionHostProcess.js:1094
stack trace: TypeError: Cannot read property 'uri' of null
	at /home/jmgd/Documents/projects/oss/foam/packages/foam-vscode/out/features/dataviz.js:121:82
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:801)
	at Object.$onMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:863:582)
	at m._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:892:926)
	at m._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:892:618)
	at m._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:891:252)
	at m._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:890:6)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:888:136
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:801)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:787)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1094:104
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:801)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:787)
	at Object._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:238:1004)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:927
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:801)
	at p.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:231:195)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:230:547
	at Socket.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

The problem being that, we know it can happen, so the exception should be handled, even if we're just logging.
Maybe in the future we can jump to the definition, but right now we should catch and log.

Furthermore, I got these blank nodes, which are inline code blocks.
image

The code that generates these is:

```md
- [Rust's FSM Ecosystem](#rusts-fsm-ecosystem)
	- [Introduction](#introduction)
	- [Existing Crates](#existing-crates)
		- [`finite-automata`](#finite-automata)
		- [`fsm`](#fsm)
		- [`macro_machine`](#macro_machine)
		- [`state-machine-future`](#state-machine-future)
		- [`mode`](#mode)
		- [`machine`](#machine)
		- [`smlang`](#smlang)
		- [`rust-fsm-dsl`](#rust-fsm-dsl)
	- [Conclusion](#conclusion)
```

I'm currently questioning if we should steer clear of crossreferences as well.

**Comment by jmg-duarte** [comment]
Cross references are still up in the graph, maybe they should be but the description for https://github.com/foambubble/foam/pull/433/commits/3401d9a8ef90b3cd215b5f42230cc110e14629ab makes me think otherwise.

image

The exception persists when clicking on a crossref node, same message.

If I can help deliver this feature I'd be pleased to do so, just point me in the right direction.

**Comment by jmg-duarte** [comment]
I just redid the build and it worked
There's an edge case but it is not a big problem, so I just suggest adding a note in the documentation before approving.

For links like `[link](../file.md#anchor)` the node will appear and when clicked, it won't go to the file, instead it throws an exception.

**Comment by jmg-duarte** [comment]
Works great!

**Review by jmg-duarte — APPROVED** [review]

**Pull request merged**
