### PR TITLE
Jump after the closing brackets (]]) on autocomplete 

### PR DESCRIPTION
**Pull request by Lauviah0622**
Reference to #962. 

- Add commit character `|` on link completion and section completion 
- Jump after the closing bracket on autocomplete except commit with `#` and `|`

### CODE REVIEW

**Review by riccardoferretti — COMMENTED** [review]
Interesting approach!
Only comment, I would put the command code together in `link-completion.ts`: given that it's only meant to serve that functionality, I think it's a bit clearer that way.

Also, given that you had to work around the API, which means the purpose of the feature is not immediately clear by looking at the code, I would add a reference to what you are accomplishing (maybe even to the issue).

Thanks for figuring this out!

**Comment by Lauviah0622** [comment]
> Only comment, I would put the command code together in link-completion.ts: given that it's only meant to serve that functionality, I think it's a bit clearer that way.

Not a problem, I split out the file cause I'm not sure are there any other feature to use it in future. But it seems too single purposely so far, I agree with move in the `link-completion.ts`

> Also, given that you had to work around the API, which means the purpose of the feature is not immediately clear by looking at the code, I would add a reference to what you are accomplishing (maybe even to the issue).

Thats a practical suggestion. I'll add some addition comment to referring to issue #962.

**Review by riccardoferretti — APPROVED** [review]
Thanks!

**Comment by riccardoferretti** [comment]
@allcontributors add @Lauviah0622 for code

**Pull request merged**
