### PR TITLE
Add recipe to fix autocompletion problems in markdown notes

### PR DESCRIPTION
**Pull request by ingalless**
This recipe isn't linked to anywhere

Completely open to any feedback and changes!

### CODE REVIEW

**Comment by ingalless** [comment]
I assume I should probably add a reference in the `recipes.md` file?

**Comment by jevakallio** [comment]
@ShaunaGordon good question. We absolutely do not have a formal guidance on US/UK English. The documentation, as written by me, is mainly British English, but I feel the internet and programming communities in particular are more accustomed to American English, so at some point we might elect to do a big refactor.

Let me noodle on this. For now, I'll keep this as UK English to conform to existing standards, and we can then convert it alongside the rest of the documentation when that day comes.

/cc @jsjoeio

**Comment by ShaunaGordon** [comment]
I personally don't care either way, for what it's worth. It's just helpful to know so we can at least _try_ to be consistent. 😁

**Comment by jevakallio** [comment]
@ingalless thank you for discovering this setting and writing the recipe 🙇 . I expanded the recipe stub and opened a new PR https://github.com/foambubble/foam/pull/180 that will land your commit as part of the rewrite

**Comment by jsjoeio** [comment]
> (Do we have any standards/conventions on British vs American English? That's the only other thing I see.)

Great call out @ShaunaGordon and thanks for the tag @ShaunaGordon. I agree, no strong opinion, but consistency is key. I'll open an issue to track this.

**Pull request closed without merging**
