### PR TITLE
[DRAFT] Query language proposal

### PR DESCRIPTION
**Pull request by pderaaij**
This PR serves as a proposal and discussion for the introduction of a query language into Foam.

### CODE REVIEW

**Review by riccardoferretti — COMMENTED** [review]
thanks for the proposal Paul!
although I like the direction per se, I wonder if it's a bit early to discuss this advanced feature as we don't yet have a plan to implement it.
I am happy to keep the PR open as an RFC for now, otherwise we could close it and create a new one when we are getting ready for an actual implementation?

**Comment by pderaaij** [comment]
I would propose to keep it open, so we can use this thread to discus functionality and value.

**Comment by riccardoferretti** [comment]
sounds good, I would just say let's change it to "draft" mode to indicate that it's still WIP

**Comment by riccardoferretti** [comment]
Closing for inactivity

**Comment by tropics1999** [comment]
I understand this is closed, but wanted to add that I would love this functionality. Prior to migrating from Obsidian I used this plugin; [https://github.com/blacksmithgu/obsidian-dataview](url)
Similarly to @pderaaij I adopted the approach for a digital garden and it is really powerful. Dataview can get quite advanced with the JS API, but I would be happy with just the SQL style language similar to what is being proposed here.

**Comment by riccardoferretti** [comment]
I love this project and I would love to have it built on top of Foam as well.
The scope is pretty big and at this point, especially considering for notes we introduces filters, I don't think it would fall into foam-core, but as a plugin for it.
But yeah, I think it's quite cool

**Comment by RensDimmendaal** [comment]
just here to say that this feature would probably make me switch from obsidian to foam.

**Comment by ZbindenDaniel** [comment]
I too worked with dataview for obsidian. I'm now trying out foam and find it very promising.  I love the idea of being able to query my documents and I think this could bring functionality to another level.

Are there any updates on this? Someone working on it or found a solution?

,Cheers 🦆

**Comment by ZbindenDaniel** [comment]
Hi

That's great! Thanks for your time

Freundliche Grüsse
Daniel Zbinden
________________________________

**Comment by charudatta10** [comment]
This repo https://github.com/sn3akiwhizper-vscode/dataview-vscode has ported dataview extension to vscode can it be used with foam @riccardoferretti ?

**Comment by riccardoferretti** [comment]
Thanks for pointing that out, I took a look at the repo. 

@sn3akiwhizper I think you got started with it, but from the code I am guessing is still in early porting, are you still thinking about pursuing the project?

**Comment by sn3akiwhizper** [comment]
Sorry but I don't have the bandwidth necessary to finish this porting effort.

**Pull request closed without merging**
