### PR TITLE
Make wikilinks more flexible

### PR DESCRIPTION
**Pull request by digiguru**
Just playing with an idea to make WikiLinks more flexible to allow alternative slug characters, capitalisation and accents yet it still generate a link to the original document.

### CODE REVIEW

**Comment by digiguru** [comment]
This is intended to fix #50. The solution I'm currently working on will allow you to be a little loser how you write links, for example 

```markdown
[[new-file]]
[[new file]]
[[New File]]
[[Néw_file]]
```

Could all parse the files present in the project, and make the assumption that if there is a file `new-file.md` which loosely matches that pattern, the author meant that link.

To be even more useful for edge cases consider the following scenario. The user has a single file in their directory `original.md`. It has the following contents...

```
#Original.md

Here's a link to a [[Zoe]]
```
The `ctrl`-`click` the file and Foam automagically creates a new file `zoe.md`, and adds link references to the bottom of the original file as follows...

```
[Zoe]: zoe "Zoe"
```
Now the author goes into the original file and changes the text as follows:

```
#Original.md

Here's a link to a [[Zoe]] and another one to [[Zoë]]
```

What should it generate? 

Option One - both link to the same location
```
[Zoe]: zoe "Zoe"
[Zoë]: zoe "Zoe"
```

Option Two - both link to separate files
```
[Zoe]: zoe "Zoe"
[Zoë]: zoë "Zoë"
```

Perhaps it does Option One until the user has created the second file with a better match. Basically it finds an exact match first, and if it fails to find one it tries to find a loose match (ignoring punctuation, capitalisation and accents).

**Comment by jevakallio** [comment]
@digiguru thanks for this! I look forward to testing and reviewing this thoroughly when I get a chance tomorrow! @riccardoferretti and I were just talking about the requirements for link formats today and came to the conclusion that we need to support [[Titles As Links]] etc, and these will be a nice test case.

**Comment by digiguru** [comment]
This is still WIP but please let me know if it fits your vision.

I have a query about backlinks. I'm writing test cases and trying to simplify as I go. Right now I can't see anywhere in the codebase that uses backlinks. Is this just a promise to have backlinks (as referenced in [[Materialized Backlinks]]?). In which case you want to have an array of all files which reference the file you are working on right now. I can look at adopting this loose linking style for that as well, but it may incur an even more major modification. I'll try and keep the commits readable.

**Comment by digiguru** [comment]
So I've made a fairly chuncky refactor to the `WorkspaceManager` to get the desired behaviour I wanted. Namely as follows.

### Dropped Maps in favour of Arrays

Maps are great for fast lookup, but only when IDs match. Because I've added this fuzzy lookup it felt like it was more work to maintain the Map way of working. I was struggling to get the IDs being consistent, and I thought of edge cases (like renaming files) where you have to guard yourself so much I thought it behaved more like an array. If you want performance we can consider reintroducing them once we have a clear idea of the behaviour.

### Links and backlinks are updated when we request them

A lot of the logic to do linking and backlinking seemed to reside in `addNote(note: Note): Note`. It felt that this was a duplicate because it also did some work in `getNoteWithLinks(id: ID): NoteWithLinks | null`. I decided the best time to calculate links was at the last possible moment, so I do it in `getNoteWithLinks`...

```javascript
  public getNoteWithLinks(id: ID): NoteWithLinks | null {
    const file = new LooseFilename(id);

    this.associateAllForwardLinks();
    this.associateAllBacklinks();

    return this.findBestMatch(file)!;
  }
```

It feels easier to understand for me, but again may have a detrimental effect on performance.

###Remove Item

I've spotted that removeItem is now really straightforawrd due to the change in the API, so I've put it back in the test suite, and made it pass.

###New Tests

I have introduce a number of new Unit Tests to ensure the logic is working.

```
✅ links things correctly when the original file has different capitalisation
✅ links things correctly when the link has different capitalisation
✅ links with a loose accent match
✅ links to the most specific match
✅ backlinks with a loose accent match
✅ updates document content
✅ updates can update back links
✅ updates can update forward links
❌ backlinks with a specific accent match // Need to figure out whats happening with backlinks when there is a fuzzy and specific match
✅ updates links correctly when page is removed
```

Once I figure out what is happening in `backlinks with a specific accent match` I will be ready for a revies, so any early feedback you have would be very welcome.

**Comment by jevakallio** [comment]
@digiguru wow, this looks amazing!

I'm sorry I didn't mention this sooner, but we've been working on an evolution of the workspace manager concept to move from string parsing to Markdown AST-parsing, and from the WorkspaceManager lookup tables to a `graphlib` graph data structure.

The first part of that work is already merged in https://github.com/foambubble/foam/pull/78

The second part is going in soon at https://github.com/foambubble/foam/pull/83

As such, this refactor won't be able to land in its current form, but there's tons of good stuff related to wiki link formatting that we absolutely need to make use of!

In the short term, if you're interested, please join us on the #foam-core channel on [Discord](https://discord.gg/rtdZKgj) so we can avoid stepping on each other's toes in the future?

**Comment by digiguru** [comment]
No worries. I suspected I was working on similar things. Scanning the work you've all done on the repo it looks soooo much easier to work with. The classes have been nicely factored into different responsibilities and that allows the test cases to behave nicer.

I can see exactly where my changes so go in the new branch so when I have time to look at this I will branch from #83

I'll try to follow discord but I find it more draining on my time than long form communication, but would certainly have made me branch from the new codebase.

**Comment by jevakallio** [comment]
> I'll try to follow discord but I find it more draining on my time than long form communication, but would certainly have made me branch from the new codebase.

Man, I feel you. When I'm doing focused work, I block Discord, Twitter etc off for 55 minutes at a time and take a distraction break to catch up on anything at the end of the hour.

Happy to work with you in whatever form you prefer!

In all honesty, chat room ops is the easy/lazy choice, we should invest more into a long-form async collaboration culture once things stabilise a bit.

> I can see exactly where my changes so go in the new branch so when I have time to look at this I will branch from #83

I'll try to land that today, so you should be able to rebase off of that!

**Comment by digiguru** [comment]
Future work will be done on #103

**Pull request closed without merging**
